version: '3.8'
services:

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    container_name: db
    restart: unless-stopped
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  
  web:
    image: sergeiban/foodgram
    container_name: web
    restart: unless-stopped
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  
  nginx:
    image: nginx:1.19.3
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    
    depends_on:
      - web
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --renew --email s.o.banshchikov@yandex.ru -d liubliusyr.ddns.net --agree-tos
volumes:
  static_value:
  media_value:
