# Generated by Django 4.1.2 on 2022-10-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='recipe',
            new_name='recipes',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='recipe',
            new_name='recipes',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='picture',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, upload_to='recipes/images/'),
        ),
    ]
