# Generated by Django 4.1.2 on 2022-10-11 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='recipes.recipeingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient'),
        ),
    ]
