# Generated by Django 4.1.2 on 2022-10-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_rename_favourite_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipes',
            field=models.ManyToManyField(null=True, to='recipes.recipe'),
        ),
    ]
