# Generated by Django 4.1.2 on 2022-10-14 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_favorite_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='recipes',
        ),
        migrations.AddField(
            model_name='cart',
            name='recipes',
            field=models.OneToOneField(default=9, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
            preserve_default=False,
        ),
    ]
