# Generated by Django 4.1.2 on 2022-10-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_alter_cart_options_alter_cart_recipe_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'В корзине', 'verbose_name_plural': 'В корзине'},
        ),
    ]
