# Generated by Django 4.1.2 on 2022-10-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
    ]
