# Generated by Django 4.1.2 on 2022-10-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_subsciptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsciptions',
            new_name='Subsciption',
        ),
    ]
