# Generated by Django 4.1.2 on 2022-10-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_subsciptions_subsciption'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsciption',
            new_name='Subscribe',
        ),
    ]
