# Generated by Django 4.1.2 on 2022-10-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_subscribe_subscribe_subscriber_author_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscriptions',
        ),
    ]
