# Generated by Django 4.1.2 on 2022-10-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_user_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('subscriber', models.F('author')), _negated=True), name='no_self_subscribing'),
        ),
    ]
