# Generated by Django 4.1.2 on 2022-10-26 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_subscribe_no_self_subscribing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
