# Generated by Django 4.1.2 on 2022-10-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_subscribe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
