# Generated by Django 4.1.2 on 2022-10-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_subscribe_author_alter_subscribe_subscriber_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
